swagger: "2.0"
info:
  version: 1.0.0
  title: API de gestion de projets
  description: API permettant la gestion de projets
host: localhost:3000
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /projects:
    get:
      summary: Récupérer tous les projets
      description: Renvoie tous les projets stockés en base de données
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal Server Error

    post:
      summary: Créer un projet
      description: Créer un nouveau projet en base de données
      consumes:
        - multipart/form-data
      parameters:
        - name: title
          in: formData
          type: string
          required: true
          description: Titre du projet
        - name: description
          in: formData
          type: string
          required: true
          description: Description du projet
        - name: technologies
          in: formData
          type: array
          items:
            type: string
          required: true
          description: Technologies utilisées pour le projet
        - name: images
          in: formData
          type: file
          required: true
          description: Image associée au projet
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal Server Error

  /projects/{id}:
    get:
      summary: Récupérer un projet
      description: Renvoie le projet correspondant à l'ID fourni
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: ID du projet à récupérer
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error

    put:
      summary: Mettre à jour un projet
      description: Met à jour le projet correspondant à l'ID fourni
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: ID du projet à mettre à jour
        - name: title
          in: formData
          type: string
          required: true
          description: Titre du projet
        - name: description
          in: formData
          type: string
          required: true
          description: Description du projet
        - name: technologies
          in: formData
          type: array
          items:
            type: string
          required: true
          description: Technologies utilisées pour le projet
        - name: images
          in: formData
          type: file
          required: true
          description: Image associée au projet
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
